version: '3.8'

services:
    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: webserver
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/apache/sites-available:/etc/apache2/sites-available
            - ./docker/apache/sites-enabled:/etc/apache2/sites-enabled
        networks:
            - laravel

    db:
        image: mysql:8
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

volumes:
    mysql_data:

networks:
    laravel:
