version: '3.8'

services:
    app:
        image: php:8.2-fpm
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel
        command: sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm"

    webserver:
        image: php:8.2-apache
        container_name: webserver
        depends_on:
            - app
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/apache/sites-available:/etc/apache2/sites-available
            - ./docker/apache/sites-enabled:/etc/apache2/sites-enabled
        networks:
            - laravel

    db:
        image: mysql:8
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

volumes:
    mysql_data:

networks:
    laravel:
